export { default as Home } from './Home'
export { default as RoomPage } from './RoomPage'
export { default as ServicePage } from './ServicePage'
export { default as RoomDetail } from './RoomDetail'
export { default as BookingPage } from './BookingPage'
export { default as ProfilePage } from './ProfilePage'
export { default as PromotionPage } from './PromotionPage'