export { default as AdminDashboard } from './AdminDashboard'
export { default as AdminRooms } from './AdminRooms'
export { default as AdminServices } from './AdminServices'
export { default as AdminBookings } from './AdminBookings'
export { default as AdminGuests } from './AdminGuests'
export { default as AdminPromotions } from './AdminPromotions'